org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.suppressUnsupportedCompileSdk=37,37.0
xposedTargetPackage=com.qzone
xposedProjectName=XposedDemo
xposedModuleName=XposedDemo
xposedModulePackage=dev.xuanran.xposeddemo
xposedLogTag=XposedDemo
xposedPreferencesName=xposed_demo
kotlin.code.style=official
